### ISSUE TITLE
Future development of Higurashi patches

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#1]
cc @ItaloKnox, @DoctorDiablo, @Grelo, @jwgrlrrajn

## Current problems

- Installing a patch requires too many steps.
- More complications if I want both PS3 and MG sprites.
- Graphics take too much disk space.
- Voice directories contain unused files.
- Some voices or images may not work on Linux because of case sensitivity.

## Features and goals

Long story short this tool already deals with all the issues above. However it works fine for my needs only and requires more work and some changes to our development porcess if we want to make things better for everyone.

### Single repository using Git LFS

The thing is we can create a single repository for each Higurashi episode and have it contain all voices graphics and scripts directly. We're not doing that at the moment because Git has isseues with large repositories but we should be able to solve this with Git LFS. It would be more convenient for development in my opinion.

The details might get a bit long and needs discussion so I'll create a separate issue for this.

### Graphics compression

Full HD graphics are awesome but the graphics patch for each episode is extremely large - about 2.5GB per episode with Watanagashi taking it to the extreme with 3.6GB. The thing is that all the PNG files are unnecesarily large because they're not using the highest compression level PNG supports. This compiler cuts them down to 1GB for Watanagashi and around 700MB for the others.

### Voices filtering

You know how we need about 3 of the `s##` directories from the voices zip for each episode? Some episodes even require the same directories meaning that none episode needs all the files. To solve this the guide recommends symlinks to save space but that complicates the installation process even further.

This tool parses the scripts and deletes all the voice files that are not actually used for the episode. No need for any symlinks, the patch contains just what is needed for the episode.

**Using the graphics compression and voices filtering I managed to cut down the Watanagashi patch (PS3 graphics + voices + MG patch) from 4.9GB down to 1.6GB.**

### MG Sprites

With the current patches the games only work if the "Updated Character Sprites" option is enabled. "Original Character Sprites" don't work because the game will crash in some cases when a sprite is missing. Also who would want to use the old ugly sprites anyway?

On the other hand there are the new sprites created by MangaGamer which some people might prefer over the PS3 ones (I do because MG Rika looks way more cute than PS3 Rika). Of course some character sprites are missing which means making the patches fully compatible with MG Sprites requires some work. I don't think we should commit ourselves to do this for every episode. On the other hand there are already awesome [patches](https://github.com/jwgrlrrajn/higurashi-steam-sprite-mods) made by @jwgrlrrajn for Onikakushi, Watanagashi and Tatarigoroshi so why not include these as well? (Of course only if he decides to give us a permission to do so.)

The whole thing should work like this: All the PS3 graphics will go into the CG directory. If the player chooses the original sprites it will be the PS3 ones. If the player chooses updated sprites the game will use the MG sprites in CGAlt directory but if they don't exist the PS3 sprites will be used as a fallback for characters that don't have MG sprites or if any sprite like the zoom or weather variant is missing in CGAlt. We would not necessarily add all these sprites ourselves but we could easily include any sprites contributed by other people.

**This tool already copies all the PS3 sprites into the CG directory and then copies the MG patch to the CGAlt directory.**

### Fixing Linux issues

While parsing the files this tool also updates the scripts so that all the files references match the file names exactly. The resulting patch should be fully compatible with Linux systems.

### Summing up

The main goals here are to make the installation process easier by providing (ideally) just a single zip file with voices, scripts, PS3 sprited and (possibly) MG sprites included while making the patch as small as possible without any unused resources.

----

**So what do you guys think? Feel free to disagree with any of my proposals and make your own suggestions.**

**Comment by Grelo** [comment]
@enumag Sorry for the big size of the pictures im reducing it right now and will upload whole question arcs here later today.

**Comment by enumag** [comment]
@Grelo Yep, that's about the same compression this tool is able to achieve.

**Comment by jwgrlrrajn** [comment]
Cool. Sounds like a plan.

**Comment by DoctorDiablo** [comment]
Streamlining the installation process sounds awesome, and reducing disk usage is great too (as long as we're not sacrificing any quality, which it sounds like).

I'm a little hesitant about including the MG sprites though.  I'm sure people would like that feature, but I wouldn't want to force someone to switch art styles 4 chapters in, so we'd be committing to doing all that extra work for each new release.  If we do though, I think the PS3 sprites should go in CGAlt and MG in CG, which would make PS3 graphics the default option for new users.

**Comment by jwgrlrrajn** [comment]
Makes sense, although I think the reason for the PS3 sprites being in CG instead of CG Alt was so that characters with PS3 sprites but no MG sprites (e.g. Chie-sensei prior to episode 3, if MG hadn't given her sprites at all) would still show up. Not entirely sure how that works though.

**Comment by jwgrlrrajn** [comment]
I'm the one who's mostly been compiling the MG sprites as an extra patch to offer additional options to the PS3 sprites, so I don't mind if that responsibility stays with me. You guys can keep doing what you're doing for the PS3 end of things, and I can make sure everything like the zoomed-in sprites are properly represented on the MG side whenever possible.

**Comment by ItaloKnox** [comment]
Hey, man, that's rude. I like the old Ryukishi sprites. 😆 

My proposal is to reduce the workload on the user's machine and instead use this compiler to prebuild the patch. If we take updates in account, the worst offender is the graphics patch since we can't update it directly without the git workaround. I mean, for free.

Voices and scripts are small, so we can keep updating it normally with new versions since we rarely miss a lot of files. So coming back to the proposal, maybe can't we use the compiler to slim down the patch and build the binaries from there? Github can host ~2gb binaries for free without any restrictions, if we make one zip for graphics and another one for voices, then it's easiest thing ever to set up an installer that downloads, installs and updates the patch. This way we can cut more than half of the installation time and updating the patch would be pretty much painless since the update list goes server-side.

I did a bunch of these before, but only for Windows. It seems there are a substantial number of Mac users around, so we would also need to take a look at that as well. But at least for Windows I think it's a solid solution and easy to implement.

Anyway, the clock is ticking so hopefully we can reach a solution that works for everyone before next friday. My best case scenario is to use the new installation in Meakashi and then update the previous chapters after that.

**Comment by Grelo** [comment]
For everyone who wants it, i just leave it here. Graphic mod with reduced size.

https://mega.nz/#!FFcAxJpR!2E8htX7kDUaqgbh9XVvVObqAtjL5_u1DW6oXv8AN_aA

**Comment by ItaloKnox** [comment]
Nice, it seems to include all chapters. If we can the voice files now (or a list of them), I think make something based on my suggestion. For now I'll be waiting for everyone's opinion on that.

**Comment by Grelo** [comment]
If you know how to do it and it would be easier than what we have now (its easy anyway at least for me) + if it would be automatic with less interaction than @enumag described in main page then definitely go for it. But im not good in these type of things so wait for other opinions.

**Comment by enumag** [comment]
@ItaloKnox @Grelo Oh I never meant for this tool to be used by the end users. All along this was meant as a tool for us to discover and fix potential problems before making a release and to transfer all previous chapters to the new way. Sorry for the confusion.

An installer for windows is something I wanted to suggest anyway - it will be necessary if we use Git LFS anyway (I'll explain why in a separate thread). So yeah, definitely 👍 .

@DoctorDiablo Having MG sprites in CG and PS3 sprites in CGAlt is unfortunately not possible because the CG directory works as a fallback if a file is not in CGAlt, but not the other way around. As I said I don't think we should commit ourselves to make the MG patches, I just don't see why not to include them once we do have them. We would need to add a note to the installation readme that it's highly recommended to change the settings to the "original sprites" (PS3) because the updated sprites may be incomplete or unavailable for future episodes. I don't think it's a problem to force them to the other sprites later - if someone complains we will just post a link to a page describing our policy that "we're not making MG patch but if you can contribute it we will happily include it". But of course we won't go this way unless we agree on it. What do you guys think, @ItaloKnox and @Grelo ?

**Comment by Grelo** [comment]
@enumag Im personally using only PS3 sprites, if others are ok with it then do it. Im happy with how things are now but if it will be easier for others or demand is big enough for MG Sprites...thats the question.... you should make some survey and ask people xD

**Comment by ItaloKnox** [comment]
I like this, I think including the MG graphics would be nice, though I have two concerns about this:
 1. Wouldn't it further increase the development time? Since the MG sprites needs to be updated manually with the weather filters, right?
 2. Wouldn't it also increase the patch size?

Point 2 can be easily fixed since we can make it optional, I just have to set up two scripts (one with the usual CGAlt installation and another one using the new CG installation). 

Point 1 however worries me a bit. Himatsubushi still doesn't have a MG patch, so if we are committing to include them, then it's partially our responsibility to include them. **But**, I think there's no issue in providing our usual patch as always and then updating the installer to include the option to install the MG patches as well after they're released. I think that's the best scenario for us.

If that's okay for everyone, then it's also ok for me. We can do that.

**Comment by enumag** [comment]
@ItaloKnox For Watanagashi (the largest patch) we're talking about 250MB which is not that much (most disk space are the PS3 backgrounds which are needed always). And as you said it can be optional in the installation process. I don't think there is an issue with the develoment time either if we do it the way you just said (which is what I've been suggesting from the start).

@jwgrlrrajn You're ok with us including your MG patches, right?

**Comment by jwgrlrrajn** [comment]
I'm working on Himatsubushi, I just haven't been able to do it as quickly as I'd like due to finals coming up.

**Comment by jwgrlrrajn** [comment]
@enumag I'm more than okay with that.

**Comment by ItaloKnox** [comment]
@enumag I'm thinking about starting it asap, can you get me a list of all the voice files needed for Onikakushi?

@jwgrlrrajn I didn't mean it in a bad way or anything like that, just take your time. Updating the installer is pretty much painless.

**Comment by enumag** [comment]
Her you go, captain. 😄 

[onikakushi.txt](https://github.com/07th-mod/higurashi-patch-compiler/files/949342/onikakushi.txt)

**Comment by ItaloKnox** [comment]
I tried to work through the voices locally but it's such a pain the ass that I tried your compiler. I'm running it in a clean Ubuntu 16.04, with the dependencies installed.

There's an issue, though. When it finishes downloading the zips, I get this error:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'ZipArchive' not found
```

I tried to run it again with sudo but the same thing happens. Any ideas?

**Comment by enumag** [comment]
ZipArchive class should work after you run `sudo apt-get install php7.1-zip`.

The windows prerequisite comes in later when cleaning up which files are used and which are not. However I just [updated](https://github.com/07th-mod/onikakushi/commit/c286b2ca164b54c84d3a3e67fd601185afd1618a) onikakushi to fix case sensitivity so if you update both the onikakushi patch and the compiler (I removed the exception thrown on linux later on) it should work.

I recommend running the higurashi:make command with `| tee output.txt` so that you cen give me the whole output it something goes wrong.

If it doesn't show any error check the output - there should be a message `Deleted 18581 unused voice files.` - if it is not there or if it has a different number it means I screwed up the linux compatibility.

Unfortunately my upload speed sucks too and it's not about to get better any time soon. :-(

**Comment by ItaloKnox** [comment]
Man, that wasn't hard but it took a long time because I had to make some workarounds. I made a new EC2 instance just to compile the patch but it seems it didn't have enough HDD for everything. Dummy download files solved the problem, I guess.

After comparing to the list you sent me earlier, it seems to be fine. All 5118 files are there.
I just finished setting up a batch script to do the whole job, so the only thing left is to test and try to implement it inside something. It's easy to have the installer run the script in a cmd window, but I still haven't found a way to output the cmd windows ***inside*** the installer. Would it be ideal to output it inside or letting the cmd window open would not be a problem?

**Comment by enumag** [comment]
Some people might be confused about a cmd window opening but I don't think it's serious enough to bother with it. I mean it's just a cosmetic problem, right?

**Comment by ItaloKnox** [comment]
Yep, that's all. I feel more safe about running an external script instead of letting the installer run the commands itself, this also allows me to pull the newest script without changing the installer itself.

I can also have the installer warn the user about the upcoming cmd window (the script also shows what step it's doing the entire time). Since we don't have much time until Meakashi, I'll try to at least have it working with minimum user interaction. After that I can try to make it pretty.

**Comment by DoctorDiablo** [comment]
Just tried the new installer.  At first, my antivirus was giving me hell because it didn't recognize the executable, so I temporarily disabled antivirus and it started up fine.  The installer launched the cmd window and it ran for a while and made it through all the downloads, but it started giving me an error about maximum path lengths once it tried installing the.  My installation directory is "D:\Program Files (x86)\SteamLibrary\steamapps\common\Higurashi When They Cry" which is a little long on top of all the nested folders being set up during the install, so I guess it can't handle it.  I'll try installing it again somewhere else.

Does the installer spit out a log file somewhere that I can post for you?

**Comment by ItaloKnox** [comment]
I need to enable logging first, so I'll start doing that by the next version. But I think I know what's wrong, I'll do some more testing and upload a new version as soon as possible.

**Comment by ItaloKnox** [comment]
Ok, I guess the bug is "fixed". Moving on Windows is pretty shitty so I had to make a workaround to copy and delete the source, but it seems to work. Did some testing using the same path as you do and it looks fine.

You don't have to redownload the installer, just run the file ``Onikakushi Patch Installer.exe`` that is inside the ``temp`` folder in your game directory. If you deleted it, no problem, just use the installer again.

**Comment by ItaloKnox** [comment]
Hey @enumag, I've been trying to get started with the remaining chapters but it seems to do the whole process excluding the most important part, the voices. It seems to move the voices but after it finishes the work, he cleans the entire SE folder.

Can I guess that the problem is the same Onikakushi did have? My script seems to be at a comfortable position right now so it would be nice if we could release the installers and update the wiki before Meakashi is released.

**Comment by enumag** [comment]
You're still running it under linux right? Then I need to fix the scripts of the remaining chapters. I'll do it right away.

**Comment by ItaloKnox** [comment]
Yep, unfortunately that's my only reliable choice. Thanks for doing that, if everything goes okay I'll have everything ready tonight.

**Comment by enumag** [comment]
Well you're doing most of the work again. This is the least I can do for you - no problem at all!

Wata and Tata are fixed. Hima will take a few more minutes because as I need to add the compilation script for it first and then fix any issues I find with that.

**Comment by ItaloKnox** [comment]
Nah, this time I might be doing the whole thing but it wouldn't exist without everyone in this thread. If anything, I'm very grateful to be in a team that works so hard (and we still have a long way before finishing the novel).

But anyway, back to business, all the installers are properly compiled and working. There might be a bug or two I left behind, but it seems to be functional. I won't release them today because I need to take some time to prepare the release announcement and update the wiki, but tomorrow is the best day to do it since Meakashi is comming the day after.

For now let's enjoy the little time we have left before the madness begins again. After we're done with Meakashi, I hope we can come back to this to find a solution for Linux and OSX and try to make the installer a bit more complete.

**Comment by enumag** [comment]
@ItaloKnox I see the new releases and the Wiki update. Good job! Well actually that's an understatement.

**Comment by ItaloKnox** [comment]
Thanks, mate! I guess we're ready to tackle on Meakashi now. Also thanks for removing the Himatsubushi note, my finger was itching a lot to click the release button. 😆 

Now let's hope the installer will work well for everyone, I tested every chapter on my machine and it seems to work well and the path bug was fixed, so there's nothing more I couldn't find to fix. Anyway, the work ends for today but tomorrow it the real thing starts. Let's hope for a smooth development without tons of voice lines missing!

**Comment by enumag** [comment]
I'm going to read the Wiki and give it some finishing touches (like I removed nonexistent download links to Meakashi patches). I'll also test the installers tomorrow on my machine and let you know how it works.

Now I have an idea for Meakashi although I'm not sure if it's good or bad. As you know the issues with the automatic voice inserter are probably unfixable since the japanese text is different so I doubt I can achive much there. However I might be able to write a detection which lines should have voices (using the 「 and 」 characters in japanese text) and which should not. Then add empty placeholders like `PlaySE(4, "", 128, 64);` for voices everywhere where the script thinks there should be a voice line but could not find it. It might be a bit of a double-edged sword though because some voice lines have multiple text lines so some placeholders would be wrong. What do you think? Should I attemt to implement it? I'm honestly not sure if it would be good for you or not.

**Comment by ItaloKnox** [comment]
The Meakashi links were placeholders but I guess I forgot to comment them so they would not show.

And about your idea, I really like it. I think it takes more time to deal with lines *without* this solution than with lines using it. I'm totally in favor of that.

**Comment by enumag** [comment]
Alright then. I'll look into it tomorrow. (It's almost midnight for me now.) Hopefully it will make your work a bit easier this time. :-)

**Comment by DoctorDiablo** [comment]
Detecting lines that need manual correction sounds pretty helpful.  I did something like that on Umineko by looking at the numbers in the filenames to identify gaps (blahblah17 followed by blahblah19, check if blahblah18 is missing).  You solution sounds good too.

**Comment by Grelo** [comment]
I can confirm the installer works and everything is here, good job. 

P.S. Are you sure that all voices in use are there? Is it possible that some got deleted through installer? Just asking not that anything is missing.

**Comment by enumag** [comment]
@Grelo Not 100% sure, there is always the possibility that I made a mistake somewhere in the script that deletes the unused voices but about 97% sure?

**Comment by Grelo** [comment]
@enumag Ok thanks, that is good success percentage.

**Comment by enumag** [comment]
@ItaloKnox I implemented the placeholders thingy for the voice insertion script. I tried it on Himatsubushi and it inserts about 13 placeholders for every 100 inserted voice lines. For the whole Himatsubushi chapter it inserted over 2200 voice lines and 300 placeholers. That's a bit more placeholders than I expected to be honest so I'm worried about false positive placeholders. But then again those should be easier to deal with than no placeholers at all, right?

**Comment by ItaloKnox** [comment]
I think it should be ok, the number doesn't sound so far from what I fix manually. Actually it feels like I fix more lines than that, so it should fine. I usually have to double check the entire script, seems to be easy to catch false positives after I finish the whole script. Let's test it like that, if it doesn't work we can revert to the old method.

**Comment by jwgrlrrajn** [comment]
I've run into a bit of a snag getting a proper MG replacement for oisi2_8_0.png. If it was any one of his existing expressions, I could just swap the face out for the correct one, then resize, but since the expression doesn't match any existing ones, I've had to come up with my own.

This is mostly a placeholder until MG makes a proper version of this sprite, although that may never happen, so I need some feedback on this. Plus, if anyone wants to make their own version, should they be more talented at this kind of thing than I am, I'd appreciate it.
![oisi2_8_0 placeholder](https://cloud.githubusercontent.com/assets/13456824/25561936/11566e54-2d3d-11e7-8220-0092910bae7a.png)

**Comment by enumag** [comment]
@jwgrlrrajn Good enough replacement in my opinion. :-)

@ItaloKnox I tried the installers today. They all work fine,
- Windows Defender thought they were dangerous and blocked them the first time I tried to launch them.
- In the input where I select the installation directory I can't move the cursor to the end of the text when it is longer than the input.
- The same input has weird looking red background in Oni and Tata installers.
- The installers should probably delete the useless CGAlt/Alternate Chie-sensei sprites directory from the MG patch. Although maybe the better solution is to not have these directories at all in the MG patch and just use all available MG sprites by default (cc @jwgrlrrajn).

@DoctorDiablo Out of curiosity how did you manage to port Someutsushi to the PC engine? Did you do that manually or do you have some easy way to port a chapter (untranslated)? Awesome work with Someutsushi!

**Comment by ItaloKnox** [comment]
Thanks for the input, @enumag. I'll keep these in mind for Meakashi and update the others. Though I'm still not sure about fixing the antivirus issue, it seems to red flag it just because it has an .exe.

@jwgrlrrajn  If you hadn't told me it was made by you I would never know. Looks great. 👍

**Comment by DoctorDiablo** [comment]
@ItaloKnox For the antivirus issue, I think we can just add a note to the installation instructions that says that the exe might be flagged by antivirus and users can bypass that by saying they trust the file, or temporarily disabling their virus protection.

@enumag Porting Someutsushi was a fair amount of work.  I have the PS3 script file so I was able to write some code that parses it and spits out all the text and voice commands in the proper format for the PC engine.  But I had to insert all the sprites, backgrounds, and sound effects by hand because those are apparently not stored in the original script.

**Comment by ItaloKnox** [comment]
Yep, the wiki instructions actually note that this might happen. The ideal scenario would be to not need it all, and that's what I'm aiming for. Maybe not for now but for a better version of the patch.

I still have to check Someutsushi but I've also included it in our wiki. Hopefully I'll be able to play it after I finish Meakashi. If I can keep up with the current pace, the scripts should be finished in two more days.

**Comment by jwgrlrrajn** [comment]
I've updated the .zip for Watanagashi, and added a couple of different versions of the Himatsubushi patch. Since Rika and Mion are supposed to be younger in that one, I figured it would make sense to have one patch that's as pure MG as possible, then another patch that has the chibi versions of Rika and Mion instead of the MG counterparts. https://github.com/jwgrlrrajn/higurashi-steam-sprite-mods/releases/tag/1.1.0

I'm working on one that replaces the PS3 chibis' hair color with the shade from the MG sprites for consistency with their MG designs, but that's not a huge priority at the moment.

**Comment by enumag** [comment]
@ItaloKnox I found a little problem with our Himatsubushi graphics patch. The directories for weather sprites are called Night, Rain and Sunset. In the new MG patch from @jwgrlrrajn they're called night and sunset causing a naming inconsistency which would cause a bug on Linux. Since Onikakushi and Watanagashi used night, rain and sunset (without the capital letter) I think we should fix it in our graphics patch. Could you do that? (My git can't handle these giant repos.) I'll fix the hima scripts myself.

**Comment by enumag** [comment]
@ItaloKnox If you got my last comment (which I deleted) by email, please ignore it. That was my own mistake, no need to fix anything.

**Comment by enumag** [comment]
@DoctorDiablo Maybe we should post some note to https://www.reddit.com/r/visualnovels/ or somewhere that we're looking for translators to help with the console arcs? I mean as awesome as your work on Someutsushi is it is probably unknown to most people and it might be unlikely for some translator to pick up on your note in the readme. What do you think?

**Comment by DoctorDiablo** [comment]
@enumag I did post to /r/visualnovels but nobody volunteered to help.  I might try asking at Fuwanovel next.  Any exposure would help.

I've also been meaning to go back and re-edit Someutsushi to fix some of the awkward English in my original translation.

**Comment by enumag** [comment]
@DoctorDiablo Found your post there now but it's more of a release announcement than a request for help. Good luck with Fuwanovel, it would be great to get more translators for this. If some translators were willing to help but would not want to work with the scripts we could set up something like OneSky for them.

----

Now the next issue I'd like to deal with - duplicate CGs (https://github.com/07th-mod/himatsubushi/issues/15). It was not easy but I managed to add a command into this compiler that tries to detect all duplicate images in the CG directory.

It might not work in all cases so I'll need someone to check the list of duplicates for false positives. Then we can change the scripts accordingly and remove the unnecessary files.

Here is the list of what the script identified as duplicates for Onikakushi. Anyone willing to verify it?

```
Images "CG/bg_001.png" and "CG/bg_002.png" are the same.
Images "CG/bg_003.png" and "CG/bg_004.png" are the same.
Images "CG/bg_007.png" and "CG/bg_014.png" are the same.
Images "CG/bg_009.png" and "CG/bg_016.png" are the same.
Images "CG/bg_009.png" and "CG/bg_017.png" are the same.
Images "CG/bg_016.png" and "CG/bg_017.png" are the same.
Images "CG/bg_039.png" and "CG/bg_040.png" are the same.
Images "CG/bg_047.png" and "CG/bg_048.png" are the same.
Images "CG/bg_081.png" and "CG/bg_082.png" are the same.
Images "CG/bg_094.png" and "CG/bg_095.png" are the same.
Images "CG/bg_108.png" and "CG/bg_109.png" are the same.
Images "CG/bg_111.png" and "CG/bg_113.png" are the same.
Images "CG/bg_165.png" and "CG/bg_166.png" are the same.
Images "CG/bg_180.png" and "CG/bg_181.png" are the same.
Images "CG/bg_238.png" and "CG/bg_246.png" are the same.
Images "CG/bg_238.png" and "CG/bg_247.png" are the same.
Images "CG/bg_246.png" and "CG/bg_247.png" are the same.
Images "CG/me_se_de_a1.png" and "CG/me_se_de_a2.png" are the same.
Images "CG/me_se_de_b1.png" and "CG/me_se_de_b2.png" are the same.
Images "CG/me_si_him_a1.png" and "CG/me_si_him_a2.png" are the same.
Images "CG/re2b_kaiiB1_0.png" and "CG/re_si_ka_b1.png" are the same.
Images "CG/night/re2b_kaiiB1_0.png" and "CG/night/re_si_ka_b1.png" are the same.
```

There is no check if the files are actually used in the scripts yet. Removing unused files is the next thing on my todo list.

**Comment by Grelo** [comment]
@enumag I can verify they are correct and think thats almost all for duplicates in that chapter, gj. You forgot, bg_007-014-015 and Bg_009-016-017 are same. Just little tweaking for triplets and higher and compiler will be good.

**Comment by enumag** [comment]
@Grelo Thank you! I'll see why the script missed them and try to improve it.

**Comment by enumag** [comment]
@Grelo I changed a constant in the script and it now identifies the images you mentioned as the same. It also found a new pait CG/bg_067.png and CG/bg_119.png.

I'll update the scripts accordingly now. The files will be removed from our patch later when I add a way to remove unused CGs.

**Comment by enumag** [comment]
I'm done with Onikakushi and Watanagashi. And let me tell you that Watanagashi was a real mess. There were way too many duplicates (https://github.com/07th-mod/watanagashi/commit/1702daf9753e33b7f962d6bfe59a99dbb052606a), not to mention over 700 unused files. No wonder that Watanagashi graphics patch was so big.

**Comment by enumag** [comment]
@ItaloKnox I think I should write you a little guide what to do with the improved compiler and the compiled files. This will require a bit more effort to achieve the best results.

1) Install this compiler. If already installed, pull the latest version. You can use Linux.

2) Aside from this compiler you'll need the MG gamefiles (unpatched) on the same machine. Change the paths in src/Constants.php (the lines at the top of the class) to match the paths to the files.

3) To make sure you will use the latest patches delete everything in the temp/ directory of the compiler (you can keep the .gitkeep file).

4) Run `php console.php higurashi:make onikakushi | tee temp/onikakushi.log`. This will easily take about half an hour or more to complete. You can check the log if you want to.

5) Now it depends on whether you want to push the newly compiled patch to GitLab ight away or want to test it first. I'm quite confident it does not remove any used CGs and sprites but you might want to play it safe nad test it yourself or upload a zip somewhere for other people to test it.

6) When you want to put it to gitlab I recommend setting up a new orphan branch (here is a stack overflow link how to do it: http://stackoverflow.com/questions/15034390/how-to-create-a-new-and-empty-root-branch) to get rid of the history of the repository. With this the repository just might become cloneable again as the files are much smaller than before. If you don't care you can skip the new branch setup. Anyway remove all files in the repo to get rid of the unused ones and copy the CG directory from the compiled patch there. Commit and push.

7) Now @jwgrlrrajn's MG sprites still have the issue of being uncompressed and contain many unused files. You can either zip the compiled CGAlt directory and upload it for @jwgrlrrajn to use for his next release or you can push it into our graphics repository as well. I'll leave this decision up to you. If you push it into our GitLab repo then update the install scripts accordingly.

You can repeat the process with Wata if you want to. Tata and Hima are not ready yet.

**Comment by ItaloKnox** [comment]
Weeeeeell, this is going to take a while so I'll keep it in mind and try to update everything before the next weekend.  It's always an improvement to kill unused files. I'll also have to release a new version, looks like you changed the scripts quite heavily so it should be the right timing for that.

By the way, how smaller did Wata become?

**Comment by enumag** [comment]
I know, sorry about it. No need to rush, though. Do it whenever convenient.

CG directory for Wata is now 527 MB with CGAlt having another 110 MB. Together with voices it is slightly less than 1 GB. Quite an improvement in my opinion - it was 1.6 GB with the first version of my compiler and about 4 GB (if not more) before we applied compression to the images.

**Comment by ItaloKnox** [comment]
Nah, it wasn't my intention to make it like I didn't want to do it. I'll try to make one a day starting from monday. I'll see if tomorrow I can implement an update feature to the patcher.

And these results are great, totally worth risking a bug or two. If we can keep this up maybe we'll be able to move the repos to github, since it's okay as long as it doesn't go past 1gb.

**Comment by jwgrlrrajn** [comment]
Unused files? Let me know when you guys have all the PS3 sprites set up then. I've mostly been playing catch-up with making sure there's MG sprites to match what you've already set up.

**Comment by jwgrlrrajn** [comment]
Just out of curiosity, in Himatsubushi, for instance, I have two different patches. One for if you prefer pure MG sprites, and one for if you would prefer Rika and Mion to have appropriately aged sprites. How does the installer handle that? Does it handle that?

**Comment by enumag** [comment]
@jwgrlrrajn It uses the appropriatly aged sprites. Which I think is a bug actually. The installer should let people choose or use MG sprites as default. @ItaloKnox ?

@DoctorDiablo I have two installation of Himatsubushi, one as regular Himatsubushi and second as Someutsushi. Is there a way to make Someutsushi have a separate directory for save files?

**Comment by ItaloKnox** [comment]
Since the MG patches are so small I just decided to install them anyway. I think it makes the patch more complete and avoids leaving a hole in the "Updated" option. So about this situation in particular, the patch doesn't handle it in a special way. It actually installs both ``himatsubushi-steam-sprites.zip`` and ``himatsubushi-steam-sprites.Chibi.PS3.zip``. Was it meant to be a single choice? If that's the case I think we should stick to the option that would make most sense to be the default. Which one would be the best?

**Comment by enumag** [comment]
@ItaloKnox Yeah it is meant as a choice between the two. The default should be `himatsubushi-steam-sprites.zip` in my opinion.

@jwgrlrrajn Just an idea - how about a patch that would use the MG sprites for Rika and Mion but make them smaller than normal to reflect their age? It would not be ideal with Mion's oversized breasts but it might be still slightly better than just using their regular MG sprites. What do you think?

**Comment by enumag** [comment]
Also maybe we should rethink which MG sprites for Chie we should use by default. This compiler uses the alternative sprites by default.

The original from MG makes her look kind of... slutty?

![tie_def](https://cloud.githubusercontent.com/assets/539462/25778542/3fac78ce-3301-11e7-9ed6-840b2b9888b9.png)

@jwgrlrrajn provides an alternative set of sprites in his patch which are much better in my opinion.

![tie_def](https://cloud.githubusercontent.com/assets/539462/25778546/509c88b8-3301-11e7-9151-15f81c39556d.png)

**Comment by jwgrlrrajn** [comment]
@enumag My original plan was to recolor the hair on the PS3 sprites to better match the MG counterparts. Rika is mostly done, but Mion has been a little more difficult. As for resizing the sprites, it could work, however, it would make the outlines a bit fuzzier. That said, Mion's bust size wouldn't be that hard to fix, since we'd really only need to fix it for one of the sprites, and the rest can just be face-swapped into the new one. Of course, this would require someone to have the ability to edit the bust size to make it look smaller to begin with, and unfortunately, I'm not one of those people.

**Comment by ItaloKnox** [comment]
Oops, I guess I misunderstood the MG patch for Himatsu. I'll update the script to only download one, but I won't scrap the idea of giving the user the choice. For now I want to concentrate on finishing the basic features and then I'll start doing chapter-specific choices.

**Comment by ItaloKnox** [comment]
I think I hit a wall in regards of doing the graphics patch cleanup. Actually it's not a issue with the compiler itself, but the environment.

First issue is my remote linux machine. I think I made so many workarounds to avoid downtime that I can't get the whole thing to work. PHP7 for starters is not doing very well and it seems that my distro is a little too old for that. No wonder since it's still running PHP4. Worst yet, the distro is refusing to update because there's something broken and I'm afraid of pulling a piece and the whole thing falling apart. Can't do that right now since it's a production server, so downtime is a no-go and it will take a couple days to restore the machine to its ideal state. For now it's something that I will only do when it's inevitable.

Second issue is with Amazon EC2. The free plan VMs have very little disk space, so compiling a graphics patch inside it is absolutely impossible. Tried with linux and windows, no avail.

My backup plan was to make a temporary Azure VM but it seems Microsoft finally realised that I dropped out college, so I'm not in the developer program anymore.

Now about something else, we got a new cover image for Umineko so I decided to make some for Higurashi as well. What do you guys think? I wanted to make the chapter names like the logo but the font is too expensive (and no torrents).
![steam_2017-05-09_15-33-37](https://cloud.githubusercontent.com/assets/4702556/25867122/00f241de-34cf-11e7-8109-f7210774ba12.jpg)

**Comment by enumag** [comment]
@ItaloKnox I might be able to add a Dockerfile to run the compiler in a Docker container. Would that help?

The images for question arcs are good but the Higurashi Kai logo in Meakashi cover is a mess.

**Comment by ItaloKnox** [comment]
I'm not well versed in Docker (actually never really understood it), but maybe we can try?

Meakashi was particularly hard because the Kai takes so much space. I think it looks better in a bigger screen but still not as good as I hoped. Maybe I'll try making the logo a little smaller to compensate.
![header](https://cloud.githubusercontent.com/assets/4702556/25867632/8e9c2a8a-34d0-11e7-944a-f40fa7a9ab88.jpg)

**Comment by enumag** [comment]
I'm not very experienced with Docker myself but this should be quite easy. Well that is if Docker Toolbox won't refuse to work like it did the last time I tried.

**Comment by ItaloKnox** [comment]
I'm giving the compiler a second try in my EC2 Ubuntu but I don't really know if I can really make it work with so little disk space. Just give me a few minutes and I'll see if it can barely fit with a few workarounds.

**Comment by enumag** [comment]
Unfortunately I didn't make the compiler friendly to disk space. It might easily need around 10GB just to compile a single chapter. I could reduce it by removing the downloaded zips after they're unpacked but it will take same time to implement.

**Comment by ItaloKnox** [comment]
Nothing that quitting the installation and making empty zips with ``touch`` wouldn't solve. For now it seems to be building the patch, let's see if it will work.

Wouldn't be much of a issue if I could use Azure, nothing that a $500/mo VM wouldn't fix for a couple hours.

**Comment by ItaloKnox** [comment]
So, there's something I forgot to ask and I'm not really sure about this, but step 7 in that mini guide you wrote above tells me to send the compiled CGAlt folder to @jwgrlrrajn. Does the compiler make anything to it to make this a necessary step?

**Comment by enumag** [comment]
@ItaloKnox Yep, quite a few things actually.

1) Compressing the images to make them smaller.
2} Filtering out unused images.
3) Adding the sprites that are normally in gamefiles to allow complete deletion of the CG and CGAlt directory before installiong the patches.

**Comment by ItaloKnox** [comment]
Good news, I guess? Hopefully there will be enough to zip them. I'm not feeling compelled to make a FTP transfer between servers, sounds like a pain in the ass.
![firefox_2017-05-09_17-09-55](https://cloud.githubusercontent.com/assets/4702556/25870407/568826f8-34da-11e7-9110-701900091ead.png)

**Comment by ItaloKnox** [comment]
Seems to be ok and enough disk space to zip the files. Thank god.
I will upload the file and give it to @jwgrlrrajn so he can update it himself. Changing the flow of the installer will require a little testing and honestly I just want to play videogames for today.

I will upload the files here after I finish Wata.

**Comment by ItaloKnox** [comment]
'k, I'm done with Onikakushi and Watanagashi. 

@enumag can you check at least one of the files to see if the whole thing is there? Didn't get any errors but we should make sure there's nothing wrong before this goes into production. Links are below. Also, can you give me an ETA for Tata and Hima?

Also @jwgrlrrajn, the links to the new MG sprites are here: http://ichigohi.me/root/?dir=higurashi
If you can update your release with them, I would be glad.

``CG = PS3``
``CGAlt = MG``
To avoid any confusion.

**Comment by enumag** [comment]
Tata should be ready although I wanted to double check it before telling you which I didn't do yet. Tomorrow I'll prepare Hima, check everything and re-read your comments to see if there is anything else I should have reacted to.

**Comment by enumag** [comment]
Himatsubushi is ready to go. Unlike Wata and Tata it didn't have too many duplicates. Tata is double-checked and good to go as well.

There is a minor issue in Hima graphics patch that ri_se_fu_a1.png is a wrong image - Rika should have different set of clothes in this image (check the other ri_se images).

**Comment by enumag** [comment]
Onikakishi patch from http://ichigohi.me/root/?dir=higurashi seems to be missing some files. Checking the reasons now but until I figure it out you should probably not progress with Tata and Hima.

**Comment by enumag** [comment]
@ItaloKnox TL;DR: The orphan branch is only a minor nice to have thing. You can just go with git rm to make the process easier for yourself.

Long version: `git rm *` keeps all the previous commits in history. Which means that when cloning you would download all the versions we ever had - that will of course fail because git can't handle such large repos. The orphan branch approach would effectively reset the history and remove the previous versions completely (well not completely but close enough). That way cloning should theoretically only download the new version of the patch which is much smaller so cloning just might work, effectively allowing other people than yourself to commit to the repository. Admittedly it is not too important as you would probably still be making most if not all the commits.

**Comment by ItaloKnox** [comment]
That's right, I always forget about the commit history. I'll set up a orphan branch and push these after I finish Hima and Tata today. Thanks a lot for checking it for me.

**Comment by ItaloKnox** [comment]
Ok, everything done and ready to go. Any reason why I should wait for @jwgrlrrajn before pushing them into the repo?

Also, this
> There is a minor issue in Hima graphics patch that ri_se_fu_a1.png is a wrong image
Should it be fixed by @Grelo?

**Comment by enumag** [comment]
No reason but you can't update the installers to delete the CGAlt directory before @jwgrlrrajn makes the release. You can delete the CG directory though.

I looked into the rika sprites and I'm not sure what to do with it. Either it's just a regular duplicate or a different sprite should be there. It would be best to check it directly in the game but I don't have save files for Hima.

**Comment by ItaloKnox** [comment]
I see, there's no problem in waiting for him, though. Better release everything together.
I'm thinking about moving the graphics patch over to Github in our resources repo. They're small enough to remotely update, zip and upload. Just need to get used to managing resources through bash.

**Comment by DoctorDiablo** [comment]
That Rika sprite was intentionally done that way because that particular scene is supposed to use the young Rika sprite.  The proper way to fix it would be to update the script to point to the young Rika variant.  It's only used once.

**Comment by enumag** [comment]
Regular duplicate then. Alright I'll fix the script. Can you remove the ri_se_fu_a1.png from the graphics patches (CG and CGAlt), @ItaloKnox?

**Comment by ItaloKnox** [comment]
Sure, I'll keep it in mind when I upload them.

**Comment by jwgrlrrajn** [comment]
I updated the Himatsubushi sprites to instead use the younger versions of Rika and Mion as detailed [here](https://github.com/07th-mod/himatsubushi/issues/16). Now that I'm a member, how do I go about pushing the updated CGalt zip to the repo?

**Comment by ItaloKnox** [comment]
[Here](https://github.com/07th-mod/resources/releases/Nipah), you should be able to edit this release and add your zips. Just be sure to follow the naming pattern, that should be ``Chapter``-CGAlt in your case. This helps us avoid installer bugs. I'll also update the wiki section about it so people won't have to go inside this repo (they're not supposed to) to download your patches.

**Comment by DoctorDiablo** [comment]
MG is[ done translating the next 3 arcs](https://twitter.com/MangaGamer/status/863121136678301696) and moving on to editing, so... we might be busy again soon.

**Comment by jwgrlrrajn** [comment]
Finished uploading the MG patches to the resources repo. Question though. My latest Himatsubushi patch uses modified versions of Rika and Mion to match their respective ages in the story; however, there may be some that would prefer the MG sprites as vanilla as possible, aside from the zoom sprites and facial expressions. Should we include an option in the installer for the vanilla MG patch?

**Comment by ItaloKnox** [comment]
@jwgrlrrajn if you provide an alternative download (can be outside of the repo or in without another name) I can try to make something. Now that the busiest work is finished, I think I can put some more work into the installer.

@DoctorDiablo I think we won't be seeing the next chapter until the last months of the year. They usually go with two chapters a year, but it would be nice if we could have three a year. I hope the next chapters aren't that big, though.

**Comment by jwgrlrrajn** [comment]
What do you mean by "in without another name?" Do you mean include all the vanilla sprites in the same zip as the modded ones?

**Comment by ItaloKnox** [comment]
Don't mind me, just woke up so my english is a bit rusty. Meant "or inside with another name". Just so it don't conflicts with the default patch.

**Comment by jwgrlrrajn** [comment]
Got it. I'll use "Himatsubushi-CGAlt-(vanilla).zip" then.

**Comment by enumag** [comment]
@DoctorDiablo When am I supposed to read the chapters myself? 😆 

@jwgrlrrajn Personally I'm against it. I think we should just deliver the best thing we agree on without bothering the user with choices. At least our updated sprites should be the defaults.

@ItaloKnox Well if the number of anime episodes they needed is any reference then Minagoroshi and Matsuribayashi are both even longer then Meakashi.

**Comment by ItaloKnox** [comment]
Just pushed the new installer script. That was a bunch of work but it was nice and now we can say that every patches follow a defined level of quality. Let's hope we can push the textbox into our next patch. 😄 

About the installer itself, I'll make it in a way where the user is not bothered with choices when installing, but running the updater will give him the option of switching to something else. I think everyone can be happy if we take this route.

@enumag Hmm... not sure if taking DEEN's adaptation would be a good comparison, but at least looking at the ``Sxy`` scripts, we did S06 which had ~5900 lines, S07 has ~2000, S08 has ~5600 and S09 has an whooping ~7200 lines script.

Maybe they're really going faster now, but I hope they don't flood us with new chapter. Even in Japan they only had two a year.

**Comment by enumag** [comment]
@ItaloKnox On the other hand MG was planning to release [14](http://www.animenewsnetwork.com/news/2015-04-03/mangagamer-licenses-higurashi-hou-myth-visual-novels/.86728) chapters in total. With 2 per year as it has been so far it would take another 5 years to finish. And even longer if they get the rights for console-only args.

**Comment by Grelo** [comment]
@ItaloKnox Good that you updated the installers but its pointless, cause you need to update voice and graphics patches to a new version too (releases), sry if you did that already.

The remaining arcs are all longer than Meakashi and maybe biggest of all 8 and skimmed through ps3 version i can tell this will be real pain in the ass and will take probably months depending how close they release them to each other.

**Comment by ItaloKnox** [comment]
You're correct, I somehow forgot to update the voice patches. Should do that asap.

**Comment by ItaloKnox** [comment]
Release all four question arcs updates. @Grelo, can you see [this](https://github.com/07th-mod/meakashi/commit/3b985b54b297493d84d0044bc9bf63d6d0159c26#commitcomment-22115574) and tell me if it's correct or if I need to change the filename? If that's correct I'll also push a new version for Meakashi.

**Comment by Grelo** [comment]
@ItaloKnox Its correct.

**Comment by enumag** [comment]
@ItaloKnox Does [this](https://github.com/07th-mod/onikakushi/blob/master/Update/README.md) need some fixing or was the file just forgotten?

**Comment by ItaloKnox** [comment]
Just forgotten, actually. Didn't even remember we had one of these inside the Update folder.

**Comment by jwgrlrrajn** [comment]
Good news, finally finished making and uploading the Meakashi-CGAlt.zip. I really wish I knew who was in charge of packaging the sprites in the official release. Most, if not all, of the sprites were slightly different sizes than their counterparts from previous episodes, meaning I had to frankensprite some of the facial expressions with what sprites episode 5 had, or I had to replace an entire character's sprites with sprites from a previous release.

Thankfully, there weren't any new facial expressions I had to resize, although I ended up having to mod one of Takano's sprites to match her new facial expression on the PS3 end. (unfortunately, Akane's going to be too difficult to do the same with).

**Comment by ItaloKnox** [comment]
Awesome, thanks for your hard work. I'll push a new update very soon so it can be installed automatically by the installer.

**Comment by enumag** [comment]
@ItaloKnox It seems the installers do not remove the CG and CGAlt directory before installing the patch resulting in some unnecessary files from the original game being left behind after the installation. I know I warned you against doing it in the past but with the new patches it should be fine.

**Comment by ItaloKnox** [comment]
Welp, you're correct. I only pushed this change for Meakashi and not for the others. Give me a second to push them.

**Comment by enumag** [comment]
Thanks. :-) With this all of the issues I was targeting with this compiler are solved now. Big thanks to all of you for making it possible! It is a real pleasure to be a part of such a great team.
